FROM jmt257/biobase:latest as app

MAINTAINER Joshua Tobin <joshua.tobin@wustl.edu>
LABEL description="Biopython, a toolset for manipulating bioinformatics datasets in python, installed on jmt257/biobase docker"
LABEL description="https://biopython.org"

ARG DEBIAN_FRONTEND=noninteractive

RUN pip install biopython


